openapi: 3.0.0

info:
  title: NOVA 15 Pricing
  version: 0.0.1-SNAPSHOT
  description: |
    
  contact:
    name: NOVA Development Team
    url: 'https://tillmannschall.github.io/nova/'
    email: noav@sbb.ch
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  # PricingService
  /nova/v15/pricing/offers/connection-offers:
    post:
      operationId: createConnectionOffers
      responses:
        '200':
          description: >- 
            TODO Please add comment
          content:  
            application/json:
              schema:
                $ref: '#/components/schemas/OfferResponse'
          
  /nova/v15/pricing/offers/trip-search-offers:
    post:
      operationId: createTripSearchOffers
      responses:
        '200':
          description: >- 
            TODO Please add comment
          content:  
            application/json:
              schema:
                $ref: '#/components/schemas/OfferResponse'
          
  /nova/v15/pricing/offers/interval-search-offers:
    post:
      operationId: createIntervalSearchOffers
      responses:
        '200':
          description: >- 
            TODO Please add comment
          content:  
            application/json:
              schema:
                $ref: '#/components/schemas/OfferResponse'
          


components:
  schemas:
    # ch.voev.nova.services.nova.v15.pricing.OfferResponse
    OfferResponse:
      type: object
      properties:
        messages: 
          type: array
          items:
            $ref: '../common/nova-common.yaml#/components/schemas/Message'
          minItems: 0

    
