openapi: 3.0.0

info:
  title: NOVA v15 Common
  version: 0.0.1-SNAPSHOT
  description: >-
    OpenAPI specification contains all those types that are valid for multiple REST resources of NOVA.
    
    Please be aware that this specfication does not offer any operations but is a pure source basic data types.
  contact:
    name: NOVA Development Team
    url: 'https://tillmannschall.github.io/nova/'
    email: nova@sbb.ch
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  # OpenAPI standard requires to define at least 1 operation. This API however seems to be a pure type definition. 
  # So we define NOP operation here as workaround.
  /nop:
    get:
      operationId: noOperation
      responses:
        '200':
          description: Nothing is the result of nop ;-)

components:
  schemas:
    # ch.voev.nova.services.nova.v15.common.Message
    Message:
      description: >-
        Type represents a message that can be returned by any NOVA REST resource. The message contains a literal description as well as a message ID that can be used to identify the message.
        
         Please be aware that depending on the message not localizations for all languages will be provided.
      type: object
      properties:
        messageID: 
          type: integer
          format: int32
          readOnly: true
        messageType: 
          $ref: '#/components/schemas/MessageType'
        localizations: 
          type: array
          items:
            $ref: '#/components/schemas/LocalizedText'
          minItems: 0
        defaultText: 
          $ref: '#/components/schemas/LocalizedText'
      required:
        - messageID
    # ch.voev.nova.services.nova.v15.common.LocalizedText
    LocalizedText:
      type: object
      properties:
        text: 
          type: string
          readOnly: true
        language: 
          type: string
          readOnly: true

    
    # ch.voev.nova.services.nova.v15.common.MessageType
    MessageType:
      description: >-
        Enumeration defines the possible types of messages that can be returned from calls to NOVA REST resources.
      type: string
      enum:
        - INFO
        - WARNING
        - ERROR

